name: Build Osx

env:
  BuildProject: PopH264.xcodeproj
  BuildScheme: PopH264_Osx

on:
  push:
    branches:
      - master
      - '*Test*'
    paths:
      - '**.yml'
      - '**Makefile'

jobs:
  Build:
    runs-on: [self-hosted, macOS]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    # https://coderwall.com/p/rv2lgw/use-xcodebuild-to-build-workspace-vs-project
    # https://github.community/t5/GitHub-Actions/steps-output/td-p/30947
    - name: GetTargetBuildDir
      id: GetTargetBuildDir
      run: |
        echo "Setting target build dir"
        echo "##[set-output name=TargetBuildDir;]$(xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme -showBuildSettings | grep TARGET_BUILD_DIR | sed -e 's/.*TARGET_BUILD_DIR = //')"
      
      # https://github.com/marketplace/actions/import-code-signing-certificates
      # create a P12 certificate, from xcode accounts, manage certificates
      # copy a base64 encoded certificate into secrets
      #   cat Certificate.p12 | base64 | pbcopy
    #- name: Import codesign certificate
    #  uses: apple-actions/import-codesign-certs@v1
    #  with:
        # on second run, we get a "keychain exists" error
    #    create-keychain: true
    #    p12-file-base64: ${{ secrets.NEWCHROMANTICS_GRAHAMREEVES_MAC_P12 }}
    #    p12-password: ${{ secrets.NEWCHROMANTICS_GRAHAMREEVES_PASSWORD_P12 }}
        
    - name: compile
      env: 
          TargetBuildDir: ${{steps.GetTargetBuildDir.outputs.TargetBuildDir}}
      run: |
          xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme -showBuildSettings
          xcodebuild -workspace $BuildProject/project.xcworkspace -list
          xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme
      
    - name: List artifacts
      env: 
          BuildDirectory: ${{steps.GetTargetBuildDir.outputs.TargetBuildDir}}

      run: |
        echo "Build Directory ($BuildDirectory) contents"
        ls $BuildDirectory
    
    # do not use env here: ##[error]Path does not exist d:\a\PopH264\PopH264\$Env:GITHUB_WORKSPACE\PopH264.visualstudio\Debug
    - uses: actions/upload-artifact@v1
      with:
        name: PopH264_Osx.framework
        path: ${{steps.GetTargetBuildDir.outputs.TargetBuildDir}}/PopH264_Osx.framework
    - uses: actions/upload-artifact@v1
      with:
        name: PopH264.h
        path: Source/PopH264.h
        
#PopH264.visualstudio\Debug\PopH264.dll
