name: Build Linux

on:
  push:
    branches:
      - ActionTest

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.container }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            name: x86_64
            container: tsdkelly/gcc_x264:latest
            Makefile: Makefile
          
          - os: ARM64
            name: arm64
            container: ""
            Makefile: Makefile
            
#         os: [ARM64, ubuntu-latest]
#         include:
#           # include variables for the matrix leg matching the os
#           - os: ARM64
#             name: arm64
#             container: ""
#             Makefile: MakefileNvidia
#           - os: ubuntu-latest
#             name: x86_64
#             container: tsdkelly/gcc_x264:latest
#             Makefile: Makefile
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile project
        run: |
          make -f ${{ matrix.config.Makefile }} GithubWorkflow -C $GITHUB_WORKSPACE/PopH264.Linux/
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.name }}
          path: |
            PopH264.Linux/PopH264${{ matrix.config.name }}.so
            PopH264.Linux/PopH264TestApp${{ matrix.config.name }}
