name: Build Linux

on:
  push:
    branches:
      - ActionTest

jobs:
  Build:
    runs-on: ubuntu-latest
    # This container can be modified to pull in the compiler for different architectures
    # https://hub.docker.com/_/gcc?tab=tags
    container: gcc
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile for arm64
        uses: ./.github/actions/LinuxBuildAction
        id: arm64
        with:
          architecture: arm64
          compiler: g++
          dockerImage: gcc
      - name: Archive the build
        uses: actions/upload-artifact@v1
        with:
          name: PopH264Test${{ env.archTarget }}
          path: ${{ steps.arm64.outputs.executable }}
