name: Build Osx

env:
  BuildProject: PopH264.xcodeproj
  BuildScheme: PopH264Framework

on: [push]

jobs:
  buildosx:
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    # https://coderwall.com/p/rv2lgw/use-xcodebuild-to-build-workspace-vs-project
      ##[set-output name=version;]$(npm run package-version --silent)"
    - name: GetTargetBuildDir
      id: GetTargetBuildDir
      run: "##[set-output name=TargetBuildDir;]xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme -showBuildSettings | grep TARGET_BUILD_DIR"

    - name: compile
      run: |
          env
          xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme -showBuildSettings | grep TARGET_BUILD_DIR
          xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme
      
    - name: List artifacts
      env: 
          TargetBuildDir: ${{steps.GetTargetBuildDir.outputs.TargetBuildDir}}

      run: |
        ls .
        ls $Env:TargetBuildDir
        ls $Env:BuildDirectory
    
    # do not use env here: ##[error]Path does not exist d:\a\PopH264\PopH264\$Env:GITHUB_WORKSPACE\PopH264.visualstudio\Debug
    - uses: actions/upload-artifact@v1
      with:
        name: PopH264.dll
        path: ${{env.BuildDirectory}}\PopH264.dll
    - uses: actions/upload-artifact@v1
      with:
        name: PopH264.lib
        path: ${{env.BuildDirectory}}\PopH264.lib
    - uses: actions/upload-artifact@v1
      with:
        name: PopH264.h
        path: Source/PopH264.h
        
#PopH264.visualstudio\Debug\PopH264.dll
