name: Build Linux

on:
  push:
    branches:
      - ActionTest

jobs:
  testEnvironment:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: finding filesystem
        run: |
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
        
#   buildlinux:
#     runs-on: ubuntu-latest
#     container:
#       image: gcc
#       volumes:
#         - $GITHUB_WORKSPACE:/build
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: true
#       - name: Build a Linux executable
#         run: |
#           ls /build
