name: Build Linux

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    env:
      project: PopH264
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            type: linux
            architecture: x86_64

          - os: Nvidia
            type: linux
            architecture: arm64

          - os: Pi4
            type: linux
            architecture: Pi4

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Linux
        uses: NewChromantics/PopAction_BuildLinux@v1
        with:
          machine: ${{ matrix.config.os }}
          architecture: ${{ matrix.config.architecture }}
          project: ${{ env.project }}
