name: Main

on:
  push:
    branches:
      - master
      - ActionTest

jobs:
  Build:
    env:
      project: PopH264
    name: ${{ matrix.config.os }}-${{ matrix.config.type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # - os: ubuntu-latest
          #   type: linux
          #   architecture: x86_64

          - os: ARM64
            type: linux
            architecture: nvidia

          # - os: windows
          #   type: windows

          - os: macOS
            type: ios
            buildScheme: PopH264_Ios

    # - os: macOS
    # type: osx
    # buildScheme: PopH264_Osx

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure Windows
        if: matrix.config.os == 'windows'
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Windows
        if: matrix.config.os == 'windows'
        uses: ./.github/actions/windows
        with:
          BuildSolution: PopH264.visualstudio\PopH264.sln
          BuildPlatform: x64
          BuildConfiguration: Release
          # would be nice to extract this from visual studio
          BuildDirectory: Build\Release_x6

      - name: Apple
        if: matrix.config.os == 'macOS'
        uses: thomasSDK/PopAppleAction@v1
        with:
          BuildScheme: ${{ matrix.config.buildScheme }}
          project: ${{ env.project }}

      - name: Linux
        if: matrix.config.type == 'linux'
        uses: thomasSDK/PopLinuxAction@v1
        with:
          architecture: ${{ matrix.config.architecture }}
          project: ${{ env.project }}

  publish-gpr:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: Build
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: Build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
